### ISSUE TITLE
Full paths for inputs causes Exception

### ISSUE THREAD

**Issue by stsci-hack** [spacetelescope/stsci.skypac#30]
Providing the full path with the input file filename causes skymatch to throw an Exception for single multi-chip exposures.  The code which causes the problem can be found in [skyline.py at Line 1035](https://github.com/spacetelescope/stsci.skypac/blob/21a26e0d86b27f0fae02b7ebf882ecb6c17c77bf/stsci/skypac/skyline.py#L1035).  
This problem can be shown by adding DEBUG log messages in this part of the code to get:
```
[INFO    ] [DEBUG] fi.count = 4
[INFO    ] [DEBUG] len(Members): 4
[INFO    ] [DEBUG] Checking member with name: /internal/1/pytest-hst/test_waiver_single0/u40x010hm_c0h.fits, u40x010hm_c0h.fits
[INFO    ] [DEBUG] Checking member with name: /internal/1/pytest-hst/test_waiver_single0/u40x010hm_c0h.fits, u40x010hm_c0h.fits
[INFO    ] [DEBUG] NFNAMES = 2 with FNAMES = ['u40x010hm_c0h.fits', 'u40x010hm_c0h.fits']
[INFO    ] [DEBUG] skyline.is_mf_mosaic = True

```
This problem was discovered when trying to process a single WFPC2 exposure from the WFPC2 Regression tests, and resulted in a KeyError when it could not find the 'MDRIZSKY' keyword.

**Comment by mcara** [comment]
@stsci-hack Could you please point to the file and how is `AstroDrizzle()` being invoked? I tried to run `astrodrizzle` on a single WFPC2 file from regression test and also using an unrelated WFPC2 file lying around and I cannot reproduce the issue.

**Comment by mcara** [comment]
@stsci-hack This should be addressed via https://github.com/spacetelescope/stsci.skypac/pull/31

@jhunkeler Let's make a release after @stsci-hack verifies that this works for him.

**Comment by mcara** [comment]
@stsci-hack Is there anybody out there?
