### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.skypac#5]
@mcara , you should make a new GitHub release and push it to AstroConda. Otherwise, end users won't pick up your fix. Also applies to the other packages that you fixed up for `drizzlepac`. FYI.

See astroconda/astroconda-contrib#159 for example.

**Comment by mcara** [comment]
I know... I am also against issues to close issues 😁 
Also see https://github.com/spacetelescope/drizzlepac/issues/31#issuecomment-278470165
