### ISSUE TITLE
major pamutils bug

### ISSUE THREAD

**Issue by yotam-stsci** [spacetelescope/stsci.skypac#51]
Hi, I'm writing concerning what I think is a bug in pamutils. This issue is on [this line](https://github.com/spacetelescope/stsci.skypac/blob/master/stsci/skypac/pamutils.py#L274).

The problem is that for some wcs (such as ones that I'm currently working with), `hasattr(wcs, 'idcscale')` returns True, but the value is None. In this case, the pam can't be generated because `_compute_pam_sd` crashes due to a TypeError on [this line](https://github.com/spacetelescope/stsci.skypac/blob/master/stsci/skypac/pamutils.py#L86).

Thanks in advance for your help.

**Comment by mcara** [comment]
> The problem is that for some wcs (such as ones that I'm currently working with)

It would be helpful to explain what kind of image has such a feature (i.e., `idcscale=None`). To the best of my knowledge, `idcscale` should not be `None` in valid HST images (CC: @stsci-hack ).

Are you sure you have run `updatewcs` on those images prior to using this software?

**Comment by yotam-stsci** [comment]
I am working with flc files that I have reduced myself from raws using CALACS.
I didn't realize that `updatewcs` had to be run on the files first, but that does make sense now, and that seems to have fixed the issue.
Thanks and sorry for the confusion!
